upstream node-exporter-host {
  server node-exporter:9100;
}

server {
  listen 9100 ssl;
  include /etc/nginx/conf.d/metrics_tls_common.inc;

  access_log /dev/null;
  server_name node-exporter;

  location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass http://node-exporter-host;
    proxy_connect_timeout 80;
    proxy_send_timeout 80;
    proxy_read_timeout 80;

    auth_basic "node-exporter-metrics";
    auth_basic_user_file /etc/nginx/conf.d/.htpasswd;
  }
}
