version: '2.1'
services:
  aio-agent:
    container_name: aio-agent
    image: prodaiotech/agentgo:e164a495
    pull_policy: always
    env_file:
      - ./.aio-env
    stdin_open: true
    environment:
      LISTEN_PORT: ":80"
    stop_grace_period: 1s
    ports:
      - 80:80
    expose:
      - "80"
