version: '2.1'
services:
  aio-agent:
    container_name: aio-agent
    image: prodaiotech/agentgo:12d8f788
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 3s
#        max_attempts: 3
#        window: 30s
    pull_policy: always
    env_file:
      - ./.aio-env
    stdin_open: true
    environment:
      LISTEN_PORT: ":80"
    stop_grace_period: 1s
    ports:
      - 80:80
    expose:
      - "80"
  proxy:
    image: prodaiotech/agent-squid:21829790
    ports:
      - "5145:5145"
    environment:
      - TZ=UTC
    env_file:
      - ./.aio-env
