services:
  aio-agent:
    container_name: aio-agent
    image: prodaiotech/agentgo:1ef5511c
    deploy:
      restart_policy:
        condition: unless-stopped
    pull_policy: always
    env_file:
      - ./.aio-env
    stop_grace_period: 0.5s
    ports:
      - 80:80
      - 443:443
      - 9200:9200
      - 6060:6060
    volumes:
      - /opt/go-cache:/go/cache
      - /opt/go-sessions:/go/sessions

  proxy:
    image: prodaiotech/agent-squid:21829790
    restart: unless-stopped
    ports:
      - "5145:5145"
    environment:
      - TZ=UTC
    env_file:
      - ./.aio-env
    stop_grace_period: 0.5s

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'
      - './tls-keys:/tls-keys'
    command:
      - '--path.rootfs=/host'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.disable-defaults'
      - '--collector.cpu'
      - '--collector.cpufreq'
      - '--collector.diskstats'
      - '--collector.filesystem'
      - '--collector.pressure'
      - '--collector.meminfo'
      - '--collector.netdev'
      - '--web.config.file=/tls-keys/exporter_conf.yml'